import {flushSync} from 'react-dom';
import {registerAtlasTools} from './agent-tools';
import {useEffect,useMemo,useRef,useState} from 'react';
import {Activity,ArrowUpRight,Camera,Check,ChevronRight,Ellipsis,Focus,Info,Layers3,Moon,Pause,Pill,RotateCcw,RotateCw,Search,Sparkles,Star,Stethoscope,Sun,Wifi,X} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Badge} from '@/components/ui/badge';
import {Slider} from '@/components/ui/slider';
import {Switch} from '@/components/ui/switch';
import {Sheet,SheetContent,SheetTitle,SheetDescription} from '@/components/ui/sheet';
import {Tabs,TabsContent,TabsList,TabsTrigger} from '@/components/ui/tabs';
import {Combobox,ComboboxInput,ComboboxContent,ComboboxList,ComboboxItem,ComboboxEmpty} from '@/components/ui/combobox';
import AnatomyScene from './scene';
import ClinicalPanel from './clinical-panel';
import RepertoryMatcher from './repertory';
import RemedyIndex from './remedy-index';
import {useNightTheme} from './night-theme';
import {offlineStatus,downloadModels,estimateMb,type OfflineStatus} from './offline-models';
import AmbientAudio from './ambient-audio';
import {BHMS_PATHOLOGY} from './bhms-pathology-data';
import {useFavorites,toggleFavorite} from './favorites';
import {DEFAULT_VISIBLE,SYSTEMS,EXPLANATIONS,explanation,type Atlas,type Concept,type SceneState,type SystemId,type View} from './anatomy';
const initial:SceneState={explode:0,visible:DEFAULT_VISIBLE,selected:[],isolate:false,view:'three-quarter',rotate:false,reset:0};
const MODEL_URL='/models/atlas.json';
export default function Home(){
 const detailTitle=useRef<HTMLHeadingElement>(null);
 const [atlas,setAtlas]=useState<Atlas|null>(null),[state,setState]=useState(initial),[progress,setProgress]=useState(0),[error,setError]=useState(''),[panel,setPanel]=useState<'layers'|'search'|'diseases'|'repertory'|'remedies'|'favorites'|null>(null),[detailTab,setDetailTab]=useState<'anatomy'|'clinical'>('anatomy'),[details,setDetails]=useState(false),[about,setAbout]=useState(false),[query,setQuery]=useState(''),[chosen,setChosen]=useState<Concept|null>(null);
 useEffect(()=>{const abort=new AbortController();setProgress(0);setError('');setAtlas(null);setChosen(null);setDetails(false);setState({...initial,visible:DEFAULT_VISIBLE});
  fetch(MODEL_URL,{signal:abort.signal}).then(r=>{if(!r.ok)throw new Error('The anatomy catalogue could not be loaded.');return r.json();}).then(data=>setAtlas(data as Atlas)).catch(e=>{if(e.name!=='AbortError')setError(e.message);});
  return()=>abort.abort();},[]);
 useEffect(()=>{const key=(e:KeyboardEvent)=>{if(e.key==='/'&&!(e.target instanceof HTMLInputElement)&&!(e.target instanceof HTMLTextAreaElement)){e.preventDefault();setPanel('search');setDetails(false);}};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key);},[]);
 const parts=useMemo(()=>new Map(atlas?.parts.map(p=>[p.id,p])),[atlas]);
 const counts=useMemo(()=>Object.fromEntries(SYSTEMS.map(s=>[s.id,atlas?.parts.filter(p=>p.system===s.id).length??0])),[atlas]);
 const activeSystems=SYSTEMS.filter(s=>counts[s.id]>0);
 const organPreset=['cardiac','respiratory','digestive','urinary','endocrine','reproductive'] as SystemId[];
 const selectedParts=state.selected.map(id=>parts.get(id)).filter(p=>!!p),selected=selectedParts[0],system=SYSTEMS.find(s=>s.id===selected?.system);
 const visibleCount=atlas?.parts.filter(p=>state.isolate?state.selected.includes(p.id):state.visible.includes(p.system)||state.selected.includes(p.id)).length??0;
 const results=useMemo(()=>{if(!atlas)return[];const term=query.toLowerCase().trim();if(!term)return ['heart','brain','liver','stomach','spleen','pancreas','urinary bladder','trachea'].map(name=>atlas.concepts.find(c=>c.name.toLowerCase()===name)).filter((x):x is Concept=>!!x);return atlas.concepts.filter(c=>c.name.toLowerCase().includes(term)||c.id.toLowerCase().includes(term)).sort((a,b)=>a.name.length-b.name.length).slice(0,80);},[atlas,query]);
 const choose=(c:Concept)=>{setChosen(c);setState(s=>({...s,selected:c.elements,isolate:false,rotate:false}));setDetailTab('anatomy');setDetails(true);setPanel(null);};
 useEffect(()=>{if(!atlas)return;return registerAtlasTools(atlas,c=>flushSync(()=>choose(c)));},[atlas]);
 const choosePart=(id:string)=>{
  closeOverlays();
  if(id.startsWith('clinical:')){const organ=id.split(':')[1],entry=BHMS_PATHOLOGY.find(e=>e.organ.toLowerCase()===organ);setChosen({id,name:entry?.organ??organ,elements:[]});setState(s=>({...s,selected:[],isolate:false,rotate:false}));setDetailTab('clinical');setDetails(true);setPanel(null);return;}
  const p=parts.get(id);if(!p)return;setChosen({id:p.conceptId,name:p.name,elements:[id]});setState(s=>({...s,selected:[id],isolate:false,rotate:false}));setDetailTab('anatomy');setDetails(true);setPanel(null);};
 const chooseDisease=(organAliases:string[],organName:string)=>{const concept=atlas?.concepts.find(c=>{const n=c.name.toLowerCase();return organAliases.some(a=>n===a||n.includes(a));})??atlas?.concepts.find(c=>c.name.toLowerCase()===organName.toLowerCase());setChosen(concept??{id:`clinical:${organName.toLowerCase()}`,name:organName,elements:[]});setState(s=>({...s,selected:concept?concept.elements:[],isolate:false,rotate:false}));setDetailTab('clinical');setDetails(true);setPanel(null);};
 const jumpToOrgan=(organName:string)=>{const entry=BHMS_PATHOLOGY.find(e=>e.organ===organName);if(entry)chooseDisease(entry.aliases,entry.organ);};
 const toggle=(id:SystemId)=>{setDetails(false);setState(s=>({...s,selected:[],isolate:false,visible:s.visible.includes(id)?s.visible.filter(x=>x!==id):[...s.visible,id]}));};
 const reset=()=>{setState(s=>({...initial,visible:DEFAULT_VISIBLE,reset:s.reset+1}));setChosen(null);setDetails(false);setPanel(null);closeOverlays();};
 const openPanel=(next:'layers'|'search'|'diseases'|'repertory'|'remedies'|'favorites')=>{setDetails(false);setMenu(false);setViewsOpen(false);setPanel(p=>p===next?null:next);};
 const [menu,setMenu]=useState(false),[viewsOpen,setViewsOpen]=useState(false);
 const toolButton=(id:'diseases'|'repertory'|'remedies'|'favorites'|'search',label:string,icon:React.ReactNode,extra?:React.ReactNode)=><Button variant="ghost" className={panel===id?'active':''} onClick={()=>openPanel(id)}>{icon}<span>{label}</span>{extra}</Button>;
 const closeOverlays=()=>{setMenu(false);setViewsOpen(false);};
 const favorites=useFavorites();
 const theme=useNightTheme();
 const [offline,setOffline]=useState<{state:OfflineStatus|'downloading';done:number;total:number}>({state:'missing',done:0,total:0});
 const swControlled=typeof navigator!=='undefined'&&!!navigator.serviceWorker?.controller;
 useEffect(()=>{if(!atlas)return;let stale=false;offlineStatus(atlas).then(s=>{if(!stale)setOffline({state:s,done:0,total:0});});return()=>{stale=true;};},[atlas]);
 const startOfflineDownload=async()=>{
  if(!atlas||offline.state==='downloading')return;
  setOffline({state:'downloading',done:0,total:0});
  await downloadModels(atlas,(done,total)=>setOffline({state:'downloading',done,total}));
  // Report readiness from the cache itself — fetch success alone can lie
  // (e.g. no service worker controlling the page).
  const s=await offlineStatus(atlas);
  setOffline({state:s,done:0,total:0});
 };
 const menuButtons=<><Button variant="ghost" className={panel==='diseases'?'active':''} onClick={()=>openPanel('diseases')} aria-label="Browse diseases"><Stethoscope size={18}/><span>Diseases</span></Button><Button variant="ghost" className={panel==='repertory'?'active':''} onClick={()=>openPanel('repertory')} aria-label="Repertory matcher"><Sparkles size={18}/><span>Repertory</span></Button><Button variant="ghost" className={panel==='remedies'?'active':''} onClick={()=>openPanel('remedies')} aria-label="Remedy index and compare"><Pill size={18}/><span>Remedies</span></Button><Button variant="ghost" className={panel==='favorites'?'active':''} onClick={()=>openPanel('favorites')} aria-label="Exam favorites"><Star size={18}/><span>Favorites{favorites.length>0&&<i className="fav-count">{favorites.length}</i>}</span></Button><Button variant="ghost" className={panel==='search'?'active':''} onClick={()=>openPanel('search')} aria-label="Search anatomy"><Search size={18}/><span>Find a structure</span><kbd>/</kbd></Button><Button variant="ghost" className="icon-button" aria-label={theme.night?'Switch to day theme':'Switch to night-study theme'} title={theme.night?'Day theme':'Night theme'} onClick={theme.toggle}>{theme.night?<Sun size={18}/>:<Moon size={18}/>}</Button><Button variant="ghost" className="icon-button" aria-label="About this atlas" onClick={()=>{setDetails(false);setPanel(null);setAbout(true);}}><Info size={18}/></Button></>;
 return <main className="studio">
  {atlas&&<AnatomyScene atlas={atlas} state={{...state,inspectorOpen:details&&!!chosen}} onSelect={choosePart} onProgress={n=>{setProgress(n);if(n===100)setError('');}} onError={setError}/>}
  <div className="vignette"/>
  <AmbientAudio/>
  <header className="identity"><div className="eyebrow"><span className="status-dot"/> BHMS CLINICAL STUDY COMPANION</div><h1>Dr. Riya's BHMS 3D Atlas<Badge variant="outline" className="edition">3D</Badge></h1><div className="identity-sub">Pathology &amp; Materia Medica for the Homeopathy student</div><div className="identity-meta">{atlas?atlas.parts.length.toLocaleString():'2,234'} modeled pieces <span>·</span> BodyParts3D</div></header>
  <nav className="top-actions" aria-label="Explorer panels">
   <div className="desktop-tools">{menuButtons}</div>
   <div className="mobile-tools">
    <Button variant="ghost" className={`icon-button menu-trigger ${menu?'active':''}`} aria-haspopup="menu" aria-expanded={menu} aria-label="Study tools menu" title="Study tools" onClick={()=>{setMenu(m=>!m);setViewsOpen(false);}}>
     <Ellipsis size={18}/>
     {favorites.length>0&&<i className="fav-count">{favorites.length}</i>}
    </Button>
    {menu&&<div className="tools-menu glass" role="menu">
     {offline.state==='available'&&<div className="offline-row ready"><Check size={16}/>Ready for offline use</div>}
     {offline.state==='downloading'&&<div className="offline-row busy"><span className="loading-track"><i style={{width:`${offline.total?Math.round(offline.done/offline.total*100):0}%`}}/></span>{offline.done}/{offline.total} downloading…</div>}
     {(offline.state==='partial'||offline.state==='missing')&&atlas&&(swControlled?<Button variant="ghost" role="menuitem" onClick={startOfflineDownload}><Wifi size={16}/><span>Download for offline{offline.state==='partial'?' (finish)':''} · ≈{estimateMb(atlas)} MB</span></Button>:<div className="offline-row"><Wifi size={16}/>Offline works after installing the app (deploy or preview build)</div>)}
     {menuButtons}
    </div>}
   </div>
  </nav>
  <section className={`layers-panel glass ${panel==='layers'?'mobile-open':''}`} aria-label="Anatomical layers">
   <div className="panel-heading"><span>Systems</span><Button variant="ghost" className="mobile-only icon-button" onClick={()=>setPanel(null)} aria-label="Close systems"><X size={18}/></Button><Badge variant="secondary" className="desktop-only small-number">{activeSystems.length}</Badge></div>
   <div className="layer-presets"><Button variant="ghost" aria-pressed={activeSystems.every(x=>state.visible.includes(x.id))} onClick={()=>setState(s=>({...s,selected:[],isolate:false,visible:activeSystems.map(x=>x.id)}))}>All</Button><Button variant="ghost" aria-pressed={state.visible.length===1&&state.visible[0]==='skeletal'} onClick={()=>setState(s=>({...s,selected:[],isolate:false,visible:['skeletal']}))}>Skeleton</Button><Button variant="ghost" aria-pressed={state.visible.length===organPreset.length&&organPreset.every(id=>state.visible.includes(id))} onClick={()=>setState(s=>({...s,selected:[],isolate:false,visible:[...organPreset]}))}>Organs</Button></div>
   <div className="system-list">{activeSystems.map(s=><div className={`system-row ${state.visible.includes(s.id)?'enabled':''}`} key={s.id}><Button variant="ghost" className="system-name" title={`Show only ${s.name.toLowerCase()}`} onClick={()=>setState(v=>({...v,visible:[s.id],isolate:false,selected:[]}))}><span className="system-dot" style={{background:s.color}}/>{s.name}<span className="system-count">{counts[s.id]}</span></Button><Switch checked={state.visible.includes(s.id)} onCheckedChange={()=>toggle(s.id)} aria-label={`Show ${s.name.toLowerCase()}`} /></div>)}</div>
   <div className="panel-foot"><span>{visibleCount.toLocaleString()} pieces visible</span><Button variant="ghost" onClick={()=>setState(s=>({...s,visible:[],selected:[],isolate:false}))}>Hide all</Button></div>
  </section>
  {panel==='search'&&<section className="search-panel glass" aria-label="Find anatomy"><div className="panel-heading"><span>Find a structure</span><Button variant="ghost" className="icon-button" onClick={()=>setPanel(null)} aria-label="Close search"><X size={18}/></Button></div><Combobox<Concept> items={results} value={null} onValueChange={value=>{if(value)choose(value);}} inputValue={query} onInputValueChange={setQuery} itemToStringLabel={c=>c.name} filter={null} open onOpenChange={open=>{if(!open)setPanel(null);}}><ComboboxInput autoFocus placeholder="Heart, femur, cranial nerve…" aria-label="Search named anatomical structures" showTrigger={false}/><ComboboxContent className="anatomy-search-results"><ComboboxEmpty>No structures match your search.</ComboboxEmpty><ComboboxList>{(c:Concept)=><ComboboxItem key={c.id} value={c}><span className="search-result-name">{c.name}</span><span className="small-number">{c.elements.length} {c.elements.length===1?'piece':'pieces'}</span></ComboboxItem>}</ComboboxList></ComboboxContent></Combobox><p className="search-note">{query?'Showing up to 80 matches. Refine your search to find smaller structures.':'Start with a major organ, or search every named structure.'}</p></section>}
  {panel==='remedies'&&<section className="repertory-panel-wrap glass" aria-label="Remedy index"><div className="panel-heading"><span>Remedy Index</span><Button variant="ghost" className="icon-button" onClick={()=>setPanel(null)} aria-label="Close remedy index"><X size={18}/></Button></div><RemedyIndex/></section>}
  {panel==='repertory'&&<section className="repertory-panel-wrap glass" aria-label="Repertory matcher"><div className="panel-heading"><span>Repertory Matcher</span><Button variant="ghost" className="icon-button" onClick={()=>setPanel(null)} aria-label="Close repertory matcher"><X size={18}/></Button></div><RepertoryMatcher/></section>}
  {panel==='favorites'&&<section className="disease-panel glass" aria-label="Exam favorites"><div className="panel-heading"><span>Exam Favorites</span><Button variant="ghost" className="icon-button" onClick={()=>setPanel(null)} aria-label="Close exam favorites"><X size={18}/></Button></div><p className="disease-note">Your starred organs and pathologies, saved on this device for viva revision.</p>{favorites.length===0?<p className="favorites-empty">Nothing starred yet — tap the ☆ next to any pathology or organ in the Clinical tab.</p>:<div className="disease-list">{favorites.map(f=><div className="disease-group fav-row" key={f.key}><Button variant="ghost" onClick={()=>jumpToOrgan(f.organ)}><Star size={13} fill="currentColor"/><span>{f.pathology??f.organ}</span><span className="small-number">{f.pathology?f.organ:''}</span></Button><Button variant="ghost" className="icon-button" aria-label={`Remove ${f.pathology??f.organ} from favorites`} onClick={()=>toggleFavorite({key:f.key,organ:f.organ,pathology:f.pathology})}><X size={14}/></Button></div>)}</div>}</section>}
  {panel==='diseases'&&<section className="disease-panel glass" aria-label="Browse diseases"><div className="panel-heading"><span>Disease Index</span><Button variant="ghost" className="icon-button" onClick={()=>setPanel(null)} aria-label="Close disease index"><X size={18}/></Button></div><p className="disease-note">Every pathology in the clinical companion — jump straight to its materia medica.</p><div className="disease-list">{BHMS_PATHOLOGY.map(entry=><div className="disease-group" key={entry.organ}><h3>{entry.organ}</h3>{entry.pathologies.map(p=><Button variant="ghost" key={p.name} onClick={()=>chooseDisease(entry.aliases,entry.organ)}><span>{p.name}</span><span className="small-number">{p.remedies.length} rx</span></Button>)}</div>)}</div></section>}
  <nav className={`view-controls glass ${viewsOpen?'open':''}`} aria-label="Camera controls"><Button variant="ghost" className="views-toggle" aria-expanded={viewsOpen} aria-label={viewsOpen?'Hide camera views':'Show camera views'} title="Camera views" onClick={()=>setViewsOpen(v=>!v)}>{viewsOpen?<X size={17}/>:<Camera size={17}/>}</Button>{viewsOpen&&<div className="views-popover">{(['three-quarter','front','side','back'] as View[]).map((v,i)=><Button variant="ghost" key={v} className={state.view===v?'active':''} aria-pressed={state.view===v} disabled={state.explode>.8&&v!=='front'} onClick={()=>setState(s=>({...s,view:v,reset:s.reset+1,rotate:false}))} title={`${v} view`} aria-label={`${v} view`}>{['¾','Front','Side','Back'][i]}</Button>)}<i/><Button variant="ghost" disabled={state.explode>=.4} aria-label={state.rotate?'Pause rotation':'Rotate body'} title="Auto rotate" className={state.rotate?'active':''} onClick={()=>setState(s=>({...s,rotate:!s.rotate}))}>{state.rotate?<Pause size={17}/>:<RotateCw size={18}/>}<span>Spin</span></Button><Button variant="ghost" aria-label="Reset view and layers" title="Reset" onClick={reset}><RotateCcw size={17}/><span>Reset</span></Button></div>}</nav>
  <div className="scene-caption"><span className="caption-line"/><span>{state.isolate?(chosen?.name??'SELECTED STRUCTURE'):state.explode>.95?'ANATOMICAL INVENTORY':state.explode>.05?'SEPARATED STRUCTURES':`ADULT HUMAN · ${(atlas?.sex??'MALE').toUpperCase()}`}</span><span className="caption-line"/></div>
  <div className="bottom-dock glass"><Button variant="ghost" className="mobile-only dock-layers" onClick={()=>openPanel('layers')} aria-label="Open system layers"><Layers3 size={20}/><span>Systems</span></Button><div className="explode-control"><div className="explode-label"><label id="explode-label">Explode anatomy</label><output>{Math.round(state.explode*100)}<span>%</span></output></div><Slider aria-labelledby="explode-label" min={0} max={100} step={1} value={[state.explode*100]} onValueChange={v=>setState(s=>({...s,explode:(Array.isArray(v)?v[0]:v)/100,view:(Array.isArray(v)?v[0]:v)>80?'front':s.view,rotate:false}))}/><div className="slider-endpoints"><span>Assembled</span><span>Every piece</span></div></div><Button variant="ghost" className="dock-reset" onClick={reset} aria-label="Assemble and reset"><RotateCcw size={18}/><span>Reset</span></Button></div>
  <footer className="studio-footer"><span>{state.explode>.8?'Drag to pan':'Drag to orbit'} <b>·</b> Pinch to zoom <b>·</b> Tap to inspect</span><Button variant="ghost" onClick={()=>{setDetails(false);setPanel(null);setAbout(true);}}>Source & credits <ArrowUpRight size={12}/></Button></footer>
  {progress<100&&!error&&<div className="loading glass" role="status"><Activity size={18}/><div><strong>Preparing the anatomy</strong><span>{progress}% · Loading {atlas?.parts.length.toLocaleString()??'2,234'} pieces</span><div className="loading-track"><i style={{width:`${progress}%`}}/></div></div></div>}
  {error&&<div className="loading glass error" role="alert"><p>{error}</p>{!navigator.onLine&&<p className="offline-hint">You appear to be offline. Open the ••• menu while online once and tap “Download for offline” to store the anatomy on this device.</p>}<Button variant="ghost" onClick={()=>location.reload()}>Reload viewer</Button></div>}
  <Sheet open={details&&!!chosen} modal={false} disablePointerDismissal onOpenChange={setDetails}><SheetContent initialFocus={detailTitle} className={`detail-sheet glass ${state.isolate?'is-isolated':''}`} showCloseButton={true}><div className="detail-header"><div className="detail-accent" style={{background:system?.color}}/><div className="eyebrow">{system?.name??'ANATOMY'}</div><SheetTitle ref={detailTitle} tabIndex={-1} className="structure-title">{chosen?.name}</SheetTitle></div><Tabs value={detailTab} onValueChange={v=>setDetailTab(v as 'anatomy'|'clinical')} className="detail-tabs"><TabsList className="detail-tab-list"><TabsTrigger value="anatomy">Anatomy</TabsTrigger><TabsTrigger value="clinical">Clinical &amp; Materia Medica</TabsTrigger></TabsList><TabsContent value="anatomy"><div className="detail-scroll" key={`${chosen?.id}-${state.isolate}`}><SheetDescription className="structure-description">{chosen&&selected?explanation(chosen.name,selected.system):''}</SheetDescription>{chosen&&!EXPLANATIONS[chosen.name.toLowerCase()]&&<span className="context-note">System overview · structure identified from source anatomy</span>}<div className="structure-meta"><span>Atlas reference<strong>{chosen?.id}</strong></span><span>Selected pieces<strong>{state.selected.length.toLocaleString()}</strong></span></div>{selectedParts.length>1&&<div className="member-list"><h3>Included structures</h3>{selectedParts.slice(0,50).map(p=><Button variant="ghost" key={p.id} onClick={()=>choosePart(p.id)}><span>{p.name}</span><ChevronRight size={14}/></Button>)}{selectedParts.length>50&&<p>And {selectedParts.length-50} more modeled pieces.</p>}</div>}<a className="source-link" href="https://lifesciencedb.jp/bp3d/" target="_blank" rel="noreferrer">View anatomical source <ArrowUpRight size={14}/></a></div></TabsContent><TabsContent value="clinical"><div className="detail-scroll clinical-scroll"><SheetDescription className="sr-only">Clinical pathology and homeopathic materia medica for the selected organ.</SheetDescription><ClinicalPanel organName={chosen?.name}/></div></TabsContent></Tabs><div className="detail-actions"><Button className={`primary-action ${state.isolate?'active':''}`} onClick={()=>setState(s=>({...s,isolate:!s.isolate,explode:0}))}><Focus size={18}/>{state.isolate?'Show surrounding anatomy':'Isolate structure'}<ChevronRight size={16}/></Button><Button variant="ghost" className="secondary-action" onClick={()=>{setState(s=>({...s,selected:[],isolate:false}));setDetails(false);}}>Clear selection</Button></div></SheetContent></Sheet>
  <Sheet open={about} onOpenChange={setAbout}><SheetContent className="about-sheet glass"><div className="eyebrow">SOURCE & SCOPE</div><SheetTitle className="structure-title">A body, revealed.</SheetTitle><SheetDescription>Explore the adult male reference anatomy from BodyParts3D.</SheetDescription><div className="about-copy"><p><strong>Male · BodyParts3D</strong><br/>2,234 individual meshes and 3,432 named concepts from an adult male reference anatomy.</p><p>This reference does not contain every human structure or variation. Named concepts can contain multiple pieces; each source mesh is rendered once.</p><p>Colors and system groupings are designed for exploration. The geometry is simplified for the web, and short explanations provide general educational context. This is an anatomical reference, not a diagnostic or surgical tool.</p><h3>Source</h3><p>BodyParts3D, © The Database Center for Life Science licensed under CC Attribution 4.0 International.</p><a href="https://dbarchive.biosciencedbc.jp/en/bodyparts3d/lic.html" target="_blank" rel="noreferrer">Dataset license <ArrowUpRight size={14}/></a><a href="https://dbarchive.biosciencedbc.jp/en/bodyparts3d/download.html" target="_blank" rel="noreferrer">Original geometry & metadata <ArrowUpRight size={14}/></a><a href="https://academic.oup.com/nar/article/37/suppl_1/D782/1000752" target="_blank" rel="noreferrer">Read the source publication <ArrowUpRight size={14}/></a></div></SheetContent></Sheet>
 </main>;
}
